### ISSUE TITLE
Error occurs if sessionId is undefined

### ISSUE THREAD

**Issue by Silverfangy** [TestArmada/magellan-saucelabs-executor#7]
Hi guys,
we encountered an issue in the Sauce Labs Executor. If the sessionId in the executor.js is undefined, an error is raised and logged to the console:
[ERROR] [Saucelabs Executor] ErrorTypeError: Cannot read property 'sessionId' of undefined

For us, this is not an error as we have an own base test class reporting to Sauce Labs and don't need the sessionId at this point. Still it is always reported as an error.
Could this be changed to a Warning? Alternatively, could you provide an example how we can set this variable in our own base test class? Or if there's no other possibility, maybe disable/filter the logging of the Sauce Labs Executor?

Thanks in advance!

**Comment by archlichking** [comment]
Hi @Silverfangy, can you tell me more about your setup to use this executor? The `undefined sessionId` issue indicates that your base test doesn't inherit from [base-test-class.js](https://github.com/TestArmada/nightwatch-extra/blob/master/src/base-test-class.js) of [nightwatch-extra](https://github.com/TestArmada/nightwatch-extra). We recommend to do so, so that you don't need to deal with reporting to Saucelabs on your own, and integration with other executors would be much easier. 

However I totally agreed that a warning makes more sense than an error here. `nightwatch-extra` isn't required to use `magellan` and all `magellan-xxx-executor`. I'll change the log type in the next release.

**Comment by Silverfangy** [comment]
Hi @archlichking! Thanks for your fast response. 
We are using your magellan setup including magellan-nightwatch-plugin, magellan-saucelabs-executor, admiral2 and magellan-admiral2-plugin. You're right, we don't use the nightwatch-extras and

**Comment by Silverfangy** [comment]
Hi @archlichking!

We are using your magellan setup including magellan-nightwatch-plugin, magellan-saucelabs-executor, admiral2 and magellan-admiral2-plugin. 
You're right, we don't use the nightwatch-extras as we currently don't see the need for it. Maybe in the future we'll include it as well, but for now our setup works smoothly and it would mean additional work to include this. We already have an own Base Test written and included in our tests which does the Sauce Labs reporting. 

That's great! 😄 Thanks for the fast response.
